### ISSUE TITLE
Milestone II Report

### ISSUE THREAD

**Issue by Melteos** [bounswe/bounswe2019group5#304]
- [x]   Executive Summary @furkan-kadioglu 
- [x]  List and Status of Deliverables @muzunpostalci 
- [x]  Evaluation of the Status of Deliverables and Their Impact of Plan @ali-deser-2016400261 
- [x] API Documentation @furkan-kadioglu 
- [x] Project Plan @nevzatersoy 
- [x] User Scenarios - Android  @haozturk 
- [x] User Scenarios - Frontend @Melteos 
- [x] Code Structure @furkan-kadioglu 
- [x] Evaluation of Tools @furkan-kadioglu 
- [x] Managing the Project @furkan-kadioglu 

- [x]  A Summary of Work Done by Each Team Member - @everyone

**Comment by furkan-kadioglu** [comment]
For backend, I have updated  List and Status of Deliverables.

**Comment by haozturk** [comment]
I have written down the Android user scenerio.

**Comment by ali-deser-2016400261** [comment]
I have written down my own part (individual section) and  Evaluation of the Status of Deliverables and Their Impact of Plan  for  Android

**Comment by Melteos** [comment]
I have added web deliverables to 2.)

**Comment by nevzatersoy** [comment]
I have added the project plan (7).

**Comment by mstniy** [comment]
This is done. The issue can be closed.
